### ISSUE TITLE
API / property to expose the text from the textarea 

### ISSUE THREAD

**Issue by dmarcos** [brianpeiris/aframe-textarea-component#3]
Better than having to access the internals:

`el.components.textarea.textarea.value`

Question popped up in [StackOverflow question](https://stackoverflow.com/questions/52405567/aframe-how-to-retrieve-the-text-from-textarea-in-aframe/52413886#52413886)

**Comment by brianpeiris** [comment]
Ah, thanks for reporting it!

**Comment by brianpeiris** [comment]
Added `getText()` in latest version.
